import type { SnapshotEntryContext } from '../src/core/types.ts'
import { mkdtemp, readdir, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { generateApiSnapshot, snapshotPackage } from '../src/core/index.ts'

const FIXTURES_DIR = join(import.meta.dirname, 'fixtures')
const SUB_EXPORTS = join(FIXTURES_DIR, 'sub-exports')

describe('entryFilter', () => {
  it('skips entries and receives package/entry context', async () => {
    const seen: SnapshotEntryContext[] = []
    const api = await generateApiSnapshot(SUB_EXPORTS, {
      entryFilter: (ctx) => {
        seen.push({ ...ctx })
        return ctx.entryName !== './utils'
      },
    })

    expect(Object.keys(api)).toEqual(['.'])
    expect(seen).toEqual([
      { packageName: 'fixture-sub-exports', entryName: '.' },
      { packageName: 'fixture-sub-exports', entryName: './utils' },
    ])
  })

  it('keeps entries when the filter returns void', async () => {
    const api = await generateApiSnapshot(SUB_EXPORTS, {
      entryFilter: () => {},
    })
    expect(Object.keys(api).sort()).toEqual(['.', './utils'])
  })
})

describe('transformEntries', () => {
  it('supports in-place mutation of the structural entries', async () => {
    const api = await generateApiSnapshot(SUB_EXPORTS, {
      header: false,
      transformEntries: (entries, { entryName, surface }) => {
        if (entryName !== '.' || surface !== 'dts')
          return
        for (const entry of entries) {
          if (entry.name === 'VERSION')
            entry.text = 'export declare const VERSION: string /* semver */;'
        }
      },
    })

    expect(api['.'].dts).toContain('export declare const VERSION: string /* semver */;')
    // Other surfaces/entries untouched
    expect(api['.'].runtime).toContain('export var VERSION /* const */')
    expect(api['./utils'].dts).toContain('export declare function slugify(_: string): string;')
  })

  it('supports returning a replacement array', async () => {
    const api = await generateApiSnapshot(SUB_EXPORTS, {
      header: false,
      transformEntries: entries => entries.filter(entry => entry.kind !== 'variable'),
    })

    expect(api['.'].runtime).not.toContain('VERSION')
    expect(api['.'].runtime).not.toContain('// #region Variables')
    expect(api['.'].runtime).toContain('export function createApp(_) {}')
    expect(api['.'].dts).not.toContain('VERSION')
  })
})

describe('transformSnapshot', () => {
  it('rewrites content per surface, keeping the header', async () => {
    const api = await generateApiSnapshot(SUB_EXPORTS, {
      transformSnapshot: ({ entryName, surface, content }) => {
        if (entryName === './utils' && surface === 'dts')
          return '/* redacted */'
        expect(content).toBeTypeOf('string')
        return null
      },
    })

    expect(api['./utils'].dts).toBe(
      '/**\n * Generated by tsnapi — public API snapshot of `fixture-sub-exports/utils`\n */\n/* redacted */',
    )
    expect(api['./utils'].runtime).toContain('export function slugify')
  })
})

describe('snapshotPackage with hooks', () => {
  let outputDir: string

  afterEach(async () => {
    if (outputDir)
      await rm(outputDir, { recursive: true, force: true })
  })

  it('applies entryFilter and transformSnapshot when writing snapshots', async () => {
    outputDir = await mkdtemp(join(tmpdir(), 'tsnapi-hooks-'))
    const result = await snapshotPackage(SUB_EXPORTS, {
      outputDir,
      entryFilter: ({ entryName }) => entryName !== './utils',
      transformSnapshot: ({ surface, content }) =>
        surface === 'dts' ? `${content}\n/* transformed */\n` : null,
    })

    expect(result.hasChanges).toBe(false)
    const files = await readdir(outputDir)
    expect(files.sort()).toEqual(['index.snapshot.d.ts', 'index.snapshot.js'])
    const dts = await readFile(join(outputDir, 'index.snapshot.d.ts'), 'utf-8')
    expect(dts).toContain('/* transformed */')
  })
})
