/**
 * Generated by tsnapi — public API snapshot of `fixture-basic`
 */
// #region Interfaces
export interface GreetOptions {
  prefix?: string;
  suffix?: string;
}
// #endregion

// #region Types
export type Formatter = (_: string) => string;
// #endregion

// #region Functions
export declare function fetchData(_: string, _?: RequestInit): Promise<Response>;
export declare function greet(_: string): string;
export declare function range(_: number, _: number): Generator<number>;
// #endregion

// #region Variables
export declare const DEBUG: boolean;
export declare const VERSION: string;
// #endregion