/**
 * Generated by tsnapi — public API snapshot of `fixture-basic` */
// Interfaces
export interface GreetOptions {
  prefix?: string;
  suffix?: string;
}

// Types
export type Formatter = (_: string) => string;

// Functions
export declare function fetchData(_: string, _?: RequestInit): Promise<Response>;
export declare function greet(_: string): string;
export declare function range(_: number, _: number): Generator<number>;

// Variables
export declare const DEBUG: boolean;
export declare const VERSION: string;