/**
 * Generated by tsnapi — public API snapshot of `unknown/client` */
// Interfaces
export interface ClientOptions {
  baseUrl: string;
  timeout?: number;
  headers?: Record<string, string>;
}

// Classes
export declare class HttpClient {
  private options;
  constructor(_: ClientOptions);
  get(_: string): Promise<Response>;
  post(_: string, _: unknown): Promise<Response>;
}

// Functions
export declare function createClient(_: ClientOptions): HttpClient;