/**
 * Generated by tsnapi — public API snapshot of `unknown/server` */
// Interfaces
export interface Middleware {
  name: string;
  handler: (_: unknown, _: unknown, _: () => void) => void;
}
export interface ServerOptions {
  port: number;
  host?: string;
  cors?: boolean;
}

// Classes
export declare class Server {
  private middlewares;
  private options;
  constructor(_: ServerOptions);
  use(_: Middleware): this;
  listen(): Promise<void>;
  close(): void;
}

// Functions
export declare function createServer(_: ServerOptions): Server;