/**
 * Generated by tsnapi — public API snapshot of `fixture-sub-exports/utils`
 */
// #region Types
export type StringTransform = (_: string) => string;
// #endregion

// #region Functions
export declare function capitalize(_: string): string;
export declare function slugify(_: string): string;
// #endregion