/**
 * Generated by tsnapi — public API snapshot of `tsnapi` */
// Interfaces
export interface ApiSnapshotOptions {
  /**
   * Snapshot output directory, relative to the project root.
   * @default '__snapshots__/tsnapi'
   */
  outputDir?: string;
  /**
   * Extension for runtime snapshot files.
   * @default '.snapshot.js'
   */
  extensionRuntime?: string;
  /**
   * Extension for DTS snapshot files.
   * @default '.snapshot.d.ts'
   */
  extensionDts?: string;
  /**
   * Add a header comment to snapshot files indicating how they were generated.
   * @default true
   */
  header?: boolean;
  /**
   * Omit argument names from function signatures.
   * When true, runtime snapshots show empty parameter lists and
   * DTS snapshots replace parameter names with `_`.
   * @default true
   */
  omitArgumentNames?: boolean;
  /**
   * Update snapshots instead of comparing.
   * When not set, auto-detected from `--update-snapshot` / `-u` CLI flags
   * or `UPDATE_SNAPSHOT=1` environment variable.
   */
  update?: boolean;
}
export interface ResolvedEntry {
  /** Export path, e.g. '.', './utils' */
  name: string;
  /** Resolved JS file path */
  runtime: string | null;
  /** Resolved DTS file path */
  dts: string | null;
}
export interface SnapshotExtensions {
  runtime: string;
  dts: string;
}
export interface SnapshotFile {
  runtime: string;
  dts: string;
}
export interface SnapshotMismatch {
  entryName: string;
  runtimeDiff: string | null;
  dtsDiff: string | null;
}
export interface SnapshotResult {
  /** Whether any snapshots mismatched */
  hasChanges: boolean;
  /** Per-entry mismatch details */
  mismatches: {
    name: string;
    runtimeChanged: boolean;
    dtsChanged: boolean;
  }[];
  /** Formatted diff output for terminal (if mismatched) */
  diff: string | null;
}

// Functions
export declare function compareSnapshots(_: string, _: SnapshotFile, _: SnapshotFile): SnapshotMismatch | null;
export declare function extractDts(_: string, _: string, _?: ExtractOptions): string;
export declare function extractRuntime(_: string, _: string, _?: ExtractOptions): string;
export declare function formatMismatchError(_: SnapshotMismatch[], _: string, _: SnapshotExtensions): string;
export declare function generateApiSnapshot(_: string, _?: ApiSnapshotOptions): Record<string, {
  runtime: string;
  dts: string;
}>;
export declare function readSnapshot(_: string, _: string, _: SnapshotExtensions): SnapshotFile | null;
export declare function resolvePackageEntries(_: string): ResolvedEntry[];
export declare function snapshotFiles(_: {
  name: string;
  runtime?: string;
  dts?: string;
}[], _: string, _?: ApiSnapshotOptions): SnapshotResult;
export declare function snapshotPackage(_: string, _?: ApiSnapshotOptions): SnapshotResult;
export declare function writeSnapshot(_: string, _: string, _: SnapshotFile, _: SnapshotExtensions, _?: string): void;