/**
 * Generated by tsnapi — public API snapshot of `tsnapi`
 */
// #region Interfaces
export interface ApiSnapshotOptions {
  outputDir?: string;
  extensionRuntime?: string;
  extensionDts?: string;
  header?: boolean;
  omitArgumentNames?: boolean;
  typeWidening?: boolean;
  categorizedExports?: boolean;
  traceDepth?: number;
  update?: boolean;
  allowBreaking?: boolean;
}
export interface BreakingChange {
  entryName: string;
  removed: string[];
  modified: string[];
  widened: string[];
  added: string[];
}
export interface ResolvedEntry {
  name: string;
  runtime: string | null;
  dts: string | null;
}
export interface SnapshotExtensions {
  runtime: string;
  dts: string;
}
export interface SnapshotFile {
  runtime: string;
  dts: string;
}
export interface SnapshotMismatch {
  entryName: string;
  runtimeDiff: string | null;
  dtsDiff: string | null;
}
export interface SnapshotResult {
  hasChanges: boolean;
  mismatches: {
    name: string;
    runtimeChanged: boolean;
    dtsChanged: boolean;
  }[];
  diff: string | null;
  breaking: BreakingChange[];
}
// #endregion

// #region Functions
export declare function analyzeApiChanges(_: string, _: SnapshotFile, _: SnapshotFile): Promise<BreakingChange>;
export declare function compareSnapshots(_: string, _: SnapshotFile, _: SnapshotFile): SnapshotMismatch | null;
export declare function extractDts(_: string, _: string, _?: ExtractOptions): Promise<string>;
export declare function extractRuntime(_: string, _: string, _?: ExtractOptions): Promise<string>;
export declare function formatBreakingChanges(_: BreakingChange[]): string;
export declare function formatMismatchError(_: SnapshotMismatch[], _: string, _: SnapshotExtensions): string;
export declare function generateApiSnapshot(_: string, _?: ApiSnapshotOptions): Promise<Record<string, {
  runtime: string;
  dts: string;
}>>;
export declare function isBreakingChange(_: BreakingChange): boolean;
export declare function readSnapshot(_: string, _: string, _: SnapshotExtensions): Promise<SnapshotFile | null>;
export declare function resolvePackageEntries(_: string): Promise<ResolvedEntry[]>;
export declare function resolvePackageEntriesSync(_: string): ResolvedEntry[];
export declare function snapshotFiles(_: {
  name: string;
  runtime?: string;
  dts?: string;
}[], _: string, _?: ApiSnapshotOptions): Promise<SnapshotResult>;
export declare function snapshotPackage(_: string, _?: ApiSnapshotOptions): Promise<SnapshotResult>;
export declare function writeSnapshot(_: string, _: string, _: SnapshotFile, _: SnapshotExtensions, _?: string): Promise<void>;
// #endregion

// #region Referenced (internal)
interface ExtractOptions {
  chunkSources?: Map<string, string>;
  omitArgumentNames?: boolean;
  typeWidening?: boolean;
  categorizedExports?: boolean;
  traceDepth?: number;
}
// #endregion