/**
 * Generated by tsnapi — API snapshot of `tsnapi/rolldown`
 * https://github.com/antfu/tsnapi
 */
// Default Export
declare function _default(_?: ApiSnapshotOptions): {
  name: string;
  generateBundle: {
    order: 'post';
    handler: (this: any, outputOptions: any, bundle: any) => void;
  };
};
export default _default