/**
 * Generated by tsnapi — public API snapshot of `tsnapi/rolldown` */
// Default Export
declare function _default(_?: ApiSnapshotOptions): {
  name: string;
  generateBundle: {
    order: 'post';
    handler: (this: any, _: any, _: any) => Promise<void>;
  };
};
export default _default