/**
 * Generated by tsnapi — public API snapshot of `tsnapi/vitest`
 */
// #region Interfaces
export interface DescribePackagesApiSnapshotsOptions extends SnapshotApiOptions {
  packages?: string[];
  cwd?: string;
  filter?: (_: PackageContext) => boolean | void;
  beforeEach?: (_: PackageContext) => void | Promise<void>;
  afterEach?: (_: PackageContext) => void | Promise<void>;
}
export interface PackageContext {
  cwd: string;
  workspaceRoot: string;
  packageRoot: string;
  packageName: string;
  outputDir: string;
}
export interface SnapshotApiOptions extends Pick<ApiSnapshotOptions, 'omitArgumentNames' | 'header'> {
  outputDir?: string;
}
// #endregion

// #region Functions
export declare function describePackagesApiSnapshots(_?: DescribePackagesApiSnapshotsOptions): void;
export declare function snapshotApiPerEntry(_: string, _?: SnapshotApiOptions): void;
// #endregion