/**
 * Generated by tsnapi — public API snapshot of `tsnapi/vitest` */
// Interfaces
export interface DescribePackagesApiSnapshotsOptions extends SnapshotApiOptions {
  packages?: string[];
  cwd?: string;
  filter?: (_: PackageContext) => boolean | void;
  beforeEach?: (_: PackageContext) => void | Promise<void>;
  afterEach?: (_: PackageContext) => void | Promise<void>;
}
export interface PackageContext {
  cwd: string;
  workspaceRoot: string;
  packageRoot: string;
  packageName: string;
  outputDir: string;
}
export interface SnapshotApiOptions extends Pick<ApiSnapshotOptions, 'omitArgumentNames' | 'header'> {
  outputDir?: string;
}

// Functions
export declare function describePackagesApiSnapshots(_?: DescribePackagesApiSnapshotsOptions): Promise<void>;
export declare function snapshotApiPerEntry(_: string, _?: SnapshotApiOptions): Promise<void>;