/**
 * Generated by tsnapi — public API snapshot of `fixture-referenced-types`
 */
// #region Interfaces
export interface ClientOptions {
  baseUrl: string;
  retry: RetryPolicyWithKind;
}
// #endregion

// #region Functions
export declare function createClient(_: ClientOptions): void;
// #endregion

// #region Variables
export declare const defaultRetry: RetryPolicy;
// #endregion

// #region Referenced (internal)
interface RetryPolicy {
  attempts: number;
  backoff: number;
}
interface RetryPolicyWithKind extends RetryPolicy {
  kind: BackoffKind;
}
// #endregion