/**
 * Generated by tsnapi — public API snapshot of `fixture-sub-exports` */
// Interfaces
export interface AppOptions {
  name: string;
  version?: string;
  debug?: boolean;
}
export interface Route {
  path: string;
  handler: () => void;
}
export interface RouterOptions {
  prefix?: string;
  routes?: Route[];
}

// Functions
export declare function createApp(_: AppOptions): {
  name: string;
  version: string;
  start: () => void;
};
export declare function createRouter(_?: RouterOptions): {
  add: (route: Route) => void;
  match: (path: string) => Route | undefined;
};

// Variables
export declare const VERSION: string;