/**
 * Generated by tsnapi — public API snapshot of `fixture-sub-exports/utils` */
// Types
export type StringTransform = (input: string) => string;

// Functions
export declare function capitalize(_: string): string;
export declare function slugify(_: string): string;