/**
 * Generated by tsnapi — public API snapshot of `unknown`
 */
// #region Interfaces
export interface FileOptions {
  encoding?: BufferEncoding;
  createDirs?: boolean;
}
// #endregion

// #region Types
export type PathLike = string | URL;
// #endregion

// #region Functions
export declare function fileExists(_: string): boolean;
export declare function joinPaths(..._: string[]): string;
export declare function readFile(_: string, _?: FileOptions): string;
export declare function writeFile(_: string, _: string, _?: FileOptions): void;
// #endregion