/**
 * Generated by tsnapi — public API snapshot of `fixture-pkg-b` */
// Types
export type Formatter = (_: string) => string;

// Functions
export declare function lowercase(_: string): string;
export declare function uppercase(_: string): string;