/**
 * Generated by tsnapi — public API snapshot of `fixture-pkg-b`
 */
// #region Types
export type Formatter = (_: string) => string;
// #endregion

// #region Functions
export declare function lowercase(_: string): string;
export declare function uppercase(_: string): string;
// #endregion