/**
 * Generated by tsnapi — public API snapshot of `fixture-pkg-a`
 */
// #region Interfaces
export interface Config {
  name: string;
  enabled: boolean;
}
// #endregion

// #region Functions
export declare function createConfig(_: string): Config;
// #endregion

// #region Variables
export declare const DEFAULT_NAME: string;
// #endregion