/**
 * Generated by tsnapi — public API snapshot of `fixture-pkg-a` */
// Interfaces
export interface Config {
  name: string;
  enabled: boolean;
}

// Functions
export declare function createConfig(_: string): Config;

// Variables
export declare const DEFAULT_NAME: string;