import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { diff } from '@vitest/utils/diff'

export interface SnapshotFile {
  runtime: string
  dts: string
}

export interface SnapshotExtensions {
  runtime: string
  dts: string
}

/**
 * Generate a header comment for snapshot files.
 */
const RE_DOT_SLASH = /^\.\//

export function generateHeader(packageName: string, entryName: string): string {
  const entryLabel = entryName === '.' ? packageName : `${packageName}/${entryName.replace(RE_DOT_SLASH, '')}`
  return `/**\n * Generated by tsnapi — public API snapshot of \`${entryLabel}\` */\n`
}

const HEADER_RE = /^\/\*\*\n \* Generated by tsnapi[\s\S]*?\*\/\n/

/**
 * Strip the tsnapi header comment from snapshot content for comparison.
 */
export function stripHeader(content: string): string {
  return content.replace(HEADER_RE, '')
}

/**
 * Write snapshot files for an entry point.
 */
export function writeSnapshot(
  outputDir: string,
  entryName: string,
  snapshot: SnapshotFile,
  ext: SnapshotExtensions,
  header?: string,
): void {
  mkdirSync(outputDir, { recursive: true })

  const runtimePath = join(outputDir, `${entryName}${ext.runtime}`)
  const dtsPath = join(outputDir, `${entryName}${ext.dts}`)

  ensureDir(runtimePath)
  ensureDir(dtsPath)

  const prefix = header ?? ''
  writeFileSync(runtimePath, prefix + normalizeSnapshotContent(snapshot.runtime), 'utf-8')
  writeFileSync(dtsPath, prefix + normalizeSnapshotContent(snapshot.dts), 'utf-8')
}

/**
 * Read existing snapshot files for an entry point.
 * Returns null if either file doesn't exist.
 */
export function readSnapshot(
  outputDir: string,
  entryName: string,
  ext: SnapshotExtensions,
): SnapshotFile | null {
  const runtimePath = join(outputDir, `${entryName}${ext.runtime}`)
  const dtsPath = join(outputDir, `${entryName}${ext.dts}`)

  if (!existsSync(runtimePath) || !existsSync(dtsPath)) {
    return null
  }

  return {
    runtime: readFileSync(runtimePath, 'utf-8').replace(/\r\n/g, '\n'),
    dts: readFileSync(dtsPath, 'utf-8').replace(/\r\n/g, '\n'),
  }
}

export interface SnapshotMismatch {
  entryName: string
  runtimeDiff: string | null
  dtsDiff: string | null
}

/**
 * Compare a new snapshot against an existing one.
 * Returns null if they match, or a mismatch with formatted diffs.
 */
export function compareSnapshots(
  entryName: string,
  existing: SnapshotFile,
  current: SnapshotFile,
): SnapshotMismatch | null {
  const currentRuntime = normalizeSnapshotContent(stripHeader(current.runtime))
  const currentDts = normalizeSnapshotContent(stripHeader(current.dts))
  const existingRuntime = normalizeSnapshotContent(stripHeader(existing.runtime))
  const existingDts = normalizeSnapshotContent(stripHeader(existing.dts))

  const runtimeDiff = existingRuntime !== currentRuntime
    ? diff(existingRuntime, currentRuntime, { expand: false, contextLines: 3 })
    : null
  const dtsDiff = existingDts !== currentDts
    ? diff(existingDts, currentDts, { expand: false, contextLines: 3 })
    : null

  if (!runtimeDiff && !dtsDiff) {
    return null
  }

  return {
    entryName,
    runtimeDiff: runtimeDiff ?? null,
    dtsDiff: dtsDiff ?? null,
  }
}

// ANSI helpers for the surrounding message (not the diff itself)
const bold = (s: string): string => `\x1B[1m${s}\x1B[22m`
const red = (s: string): string => `\x1B[31m${s}\x1B[39m`
const cyan = (s: string): string => `\x1B[36m${s}\x1B[39m`
const dim = (s: string): string => `\x1B[2m${s}\x1B[22m`

/**
 * Format the full mismatch error with pretty diffs for terminal output.
 */
export function formatMismatchError(
  mismatches: SnapshotMismatch[],
  outputDir: string,
  ext: SnapshotExtensions,
): string {
  const lines: string[] = []

  lines.push('')
  lines.push(bold(red('API snapshot mismatch detected')))
  lines.push('')

  for (const m of mismatches) {
    if (m.runtimeDiff) {
      lines.push(cyan(`  ${outputDir}/${m.entryName}${ext.runtime}`))
      lines.push('')
      lines.push(indent(m.runtimeDiff, '    '))
      lines.push('')
    }
    if (m.dtsDiff) {
      lines.push(cyan(`  ${outputDir}/${m.entryName}${ext.dts}`))
      lines.push('')
      lines.push(indent(m.dtsDiff, '    '))
      lines.push('')
    }
  }

  lines.push(dim('  Run with --update-snapshot or -u to update.'))
  lines.push('')

  return lines.join('\n')
}

function indent(text: string, prefix: string): string {
  return text.split('\n').map(line => `${prefix}${line}`).join('\n')
}

function normalizeSnapshotContent(content: string): string {
  const trimmed = content.trim()
  return trimmed || '/* no exports */'
}

function ensureDir(filePath: string): void {
  const dir = dirname(filePath)
  mkdirSync(dir, { recursive: true })
}
