/**
 * Generated by tsnapi — public API snapshot of `unknown`
 */
// #region Interfaces
export interface LoggerFactory {
  create: (_: string) => BaseLogger;
}
// #endregion

// #region Enums
export declare enum LogLevel {
  Debug = 0,
  Info = 1,
  Warn = 2,
  Error = 3
}
// #endregion

// #region Classes
export declare abstract class BaseLogger {
  abstract log(_: string): void;
  info(_: string): void;
  warn(_: string): void;
}
export declare class BufferedLogger extends BaseLogger {
  private buffer;
  log(_: string): void;
  flush(): string[];
  get size(): number;
}
export declare class ConsoleLogger extends BaseLogger {
  private prefix;
  constructor(_?: string);
  log(_: string): void;
  static create(_?: string): ConsoleLogger;
}
// #endregion