export {
  analyzeApiChanges,
  compareSnapshots,
  extractDts,
  extractRuntime,
  formatBreakingChanges,
  formatMismatchError,
  generateApiSnapshot,
  isBreakingChange,
  readSnapshot,
  resolvePackageEntries,
  resolvePackageEntriesSync,
  snapshotFiles,
  snapshotPackage,
  writeSnapshot,
} from './core/index.ts'

export type {
  ApiSnapshotOptions,
  BreakingChange,
  Entry,
  EntryKind,
  ResolvedEntry,
  SnapshotEntryContext,
  SnapshotExtensions,
  SnapshotFile,
  SnapshotMismatch,
  SnapshotResult,
  SnapshotSurface,
  TransformEntriesContext,
  TransformSnapshotContext,
} from './core/index.ts'
