/**
 * Generated by tsnapi — public API snapshot of `fixture-re-exports` */
// Interfaces
export interface Options {
  verbose?: boolean;
  timeout?: number;
}

// Types
export type Formatter = (_: string) => string;

// Classes
export declare class Service {
  private name;
  constructor(_: string);
  run(_: string): string;
}

// Functions
export declare function formatOutput(_: string): string;
export declare function process(_: string, _?: InternalOptions): string;

// Variables
export declare const VERSION: string;