/**
 * Generated by tsnapi — public API snapshot of `fixture-re-exports`
 */
// #region Interfaces
export interface Options {
  verbose?: boolean;
  timeout?: number;
}
// #endregion

// #region Types
export type Formatter = (_: string) => string;
// #endregion

// #region Classes
export declare class Service {
  private name;
  constructor(_: string);
  run(_: string): string;
}
// #endregion

// #region Functions
export declare function formatOutput(_: string): string;
export declare function process(_: string, _?: InternalOptions): string;
// #endregion

// #region Variables
export declare const VERSION: string;
// #endregion