/**
 * Generated by tsnapi — public API snapshot of `fixture-deprecated`
 */
// #region Interfaces
export interface PostOptions {
  text: string;
}
/** @deprecated */
export interface TweetOptions {
  text: string;
}
// #endregion

// #region Functions
export declare function post(_: string): string;
/** @deprecated */
export declare function tweet(_: string): string;
// #endregion

// #region Variables
export declare const APP_NAME: string;
/** @deprecated */
export declare const BIRD_NAME: string;
// #endregion